-- AlterTable
ALTER TABLE "StockLedger" ADD COLUMN     "balanceValue" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "valueIn" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "valueOut" DOUBLE PRECISION DEFAULT 0;
